run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80

  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          - $gostd
          - github.com/BurntSushi/toml
          - github.com/go-sql-driver/mysql
          - github.com/google/uuid
          - github.com/pressly/goose/v3
          - github.com/stretchr/testify/require
          - github.com/stretchr/testify/suite
          - github.com/Ruslan-Androsenko/otus-home-work/hw12_13_14_15_calendar/internal/app
          - github.com/Ruslan-Androsenko/otus-home-work/hw12_13_14_15_calendar/internal/logger
          - github.com/Ruslan-Androsenko/otus-home-work/hw12_13_14_15_calendar/internal/server/http
          - github.com/Ruslan-Androsenko/otus-home-work/hw12_13_14_15_calendar/internal/storage
          - github.com/Ruslan-Androsenko/otus-home-work/hw12_13_14_15_calendar/migrations

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
