[storage]
type = "database"

# Valid values
# [memory, database]

[storage.database]
db_host = "localhost"
db_port = 3306
db_user = "root"
db_pass = "root"
db_name = "calendar"

[queue]
queue_host = "localhost"
queue_port = 5672
queue_user = "guest"
queue_pass = "guest"

[queue.exchange]
exchange_name = "calendar-exchange"
exchange_type = "direct"
routing_key = "calendar-key"
queue_name = "calendar-queue"
consumer_tag = "calendar-tag"

# Периодичность запуска Планировщика (каждую минуту)
[queue.period]
launch_frequency="0 */1 * * * *"

[logger]
level = "INFO"

# Valid values
# [FATAL, ERROR, WARN, INFO, DEBUG]
