[server]
host = "0.0.0.0"
port = 8080

[storage]
type = "database"

# Valid values
# [memory, database]

[storage.database]
db_host = "localhost"
db_port = 3306
db_user = "root"
db_pass = "root"
db_name = "calendar"

[logger]
level = "INFO"

# Valid values
# [FATAL, ERROR, WARN, INFO, DEBUG]

# TODO
# ...
