version: "3"

services:
  calendar.service:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: calendar:compose
    container_name: calendar.service
    ports:
      - "8070:8070"
      - "8080:8080"
